Merge magic-code-name-1892
Author: exarkun
Reviewer: jml
Fixes #1892

Change trial and conch manhole tests to account for the difference in traceback
formatting between Python <=2.4 and Python >=2.5.  In Python 2.4, tracebacks
which start at the interactive interpreter or the top-level of a module look
like this:

Traceback (most recent call last):
  File "<stdin>", line 1, in ?
ZeroDivisionError: integer division or modulo by zero

In Python 2.5, the format changed to look like this:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero

These changes make the test suite work with either form.


git-svn-id: svn://svn.twistedmatrix.com/svn/Twisted/trunk@17478 bbbe8e31-12d6-0310-92fd-ac37d47ddeeb