Revert r23444 - test suite regression on FreeBSD
Reopens: #3202

This changeset introduced three test failures on FreeBSD by way of an exception
in the modified tearDown method:

{{{
===============================================================================
[ERROR]: twisted.test.test_process.UtilTestCase.testWhich

Traceback (most recent call last):
  File "/usr/home/therve/Run/slave/freebsd-py2.4-select/Twisted/twisted/test/test_process.py", line 1963, in tearDown
    os.chmod(os.path.join(self.bazbar, "executable"), 700)
exceptions.OSError: [Errno 79] Inappropriate file type or format: 'twisted.test.test_process/UtilTestCase/testWhich/lo3a1X/temp/baz/bar/executable'
===============================================================================
[ERROR]: twisted.test.test_process.UtilTestCase.testWhichPathExt

Traceback (most recent call last):
  File "/usr/home/therve/Run/slave/freebsd-py2.4-select/Twisted/twisted/test/test_process.py", line 1963, in tearDown
    os.chmod(os.path.join(self.bazbar, "executable"), 700)
exceptions.OSError: [Errno 79] Inappropriate file type or format: 'twisted.test.test_process/UtilTestCase/testWhichPathExt/VchWFn/temp/baz/bar/executable'
===============================================================================
[ERROR]: twisted.test.test_process.UtilTestCase.test_whichWithoutPATH

Traceback (most recent call last):
  File "/usr/home/therve/Run/slave/freebsd-py2.4-select/Twisted/twisted/test/test_process.py", line 1963, in tearDown
    os.chmod(os.path.join(self.bazbar, "executable"), 700)
exceptions.OSError: [Errno 79] Inappropriate file type or format: 'twisted.test.test_process/UtilTestCase/test_whichWithoutPATH/OHS-2j/temp/baz/bar/executable'
-------------------------------------------------------------------------------
}}}


git-svn-id: svn://svn.twistedmatrix.com/svn/Twisted/trunk@23447 bbbe8e31-12d6-0310-92fd-ac37d47ddeeb