Revert r23682 - Python 2.3 doctest regression
Reopens: #2713

Python 2.3 builder has a total failure inducing problem:

{{{
Traceback (most recent call last):
  File "./bin/trial", line 24, in ?
    run()
  File "/srv/bb-slave/Run/slave/full2.3/Twisted/twisted/scripts/trial.py", line 357, in run
    suite = _getSuite(config)
  File "/srv/bb-slave/Run/slave/full2.3/Twisted/twisted/scripts/trial.py", line 315, in _getSuite
    return loader.loadByNames(config['tests'], recurse)
  File "/srv/bb-slave/Run/slave/full2.3/Twisted/twisted/trial/runner.py", line 638, in loadByNames
    suites = [self.loadAnything(thing, recurse)
  File "/srv/bb-slave/Run/slave/full2.3/Twisted/twisted/trial/runner.py", line 596, in loadAnything
    return self.loadPackage(thing, recurse)
  File "/srv/bb-slave/Run/slave/full2.3/Twisted/twisted/trial/runner.py", line 551, in loadPackage
    thingToAdd = self.loadModule(module)
  File "/srv/bb-slave/Run/slave/full2.3/Twisted/twisted/trial/runner.py", line 475, in loadModule
    docSuite.addTest(self.loadDoctests(doctest))
  File "/srv/bb-slave/Run/slave/full2.3/Twisted/twisted/trial/runner.py", line 581, in loadDoctests
    return doctest.DocTestSuite(module, setUp=saveGlobs)
TypeError: DocTestSuite() got an unexpected keyword argument 'setUp'
}}}


git-svn-id: svn://svn.twistedmatrix.com/svn/Twisted/trunk@23684 bbbe8e31-12d6-0310-92fd-ac37d47ddeeb